title: little-raccoon
description: This guy is so diligent that he doesn't write anything
social_link: wechat
social_username: little raccoon
github_repo: athena
github_username: little-raccoon
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /little_raccoon_blog
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
